export const DATA_LIST_REQUEST = "DATA_LIST_REQUEST";
export const DATA_LIST_SUCCESS = "DATA_LIST_SUCCESS";
export const DATA_LIST_FAILED = "DATA_LIST_FAILED";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";

export const DATA_CREATE_REQUEST = "DATA_CREATE_REQUEST";
export const DATA_CREATE_SUCCESS = "DATA_CREATE_SUCCESS";
export const DATA_CREATE_FAIL = "DATA_CREATE_FAIL";
export const DATA_CREATE_RESET = "DATA_CREATE_RESET";

export const DATA_EDIT_REQUEST = "DATA_EDIT_REQUEST";
export const DATA_EDIT_SUCCESS = "DATA_EDIT_SUCCESS";
export const DATA_EDIT_FAIL = "DATA_EDIT_FAIL";
export const DATA_EDIT_RESET = "DATA_EDIT_RESET";

export const DATA_DELETE_REQUEST = "DATA_DELETE_REQUEST";
export const DATA_DELETE_SUCCESS = "DATA_DELETE_SUCCESS";
export const DATA_DELETE_FAIL = "DATA_DELETE_FAIL";
export const DATA_DELETE_RESET = "DATA_DELETE_RESET";
